### ISSUE TITLE
Async supprt

### ISSUE THREAD

**Issue by luizbon** [orientechnologies/OrientDB-NET.binary#105]
Is there any plans to make this library async?

**Comment by aligin** [comment]
It'll be very cool to async support. But it would be good to introduce true ASP.NET support IServiceCollection implementation without static DataBasePoolConnection.

**Comment by GrayDelacluyse** [comment]
@luizbon @aligin 
We (Innov8tive) actually just took over the development of the .Net Driver, http://orientdb.com/innov8tive-orientdb/

We are in the process of creating a roadmap, but our first focus will be on performance.  We are looking at a number of options for this and we should have more details in the near future.  However, we do support pull request and encourage community development.

Thanks,
Gray
