### ISSUE TITLE
NullReferenceException on Load non existing record

### ISSUE THREAD

**Issue by aligin** [orientechnologies/OrientDB-NET.binary#106]
I caught an interesting exception.
When loading non existing record with non existing CLUSTER I catch OExeption as expected.
But when load non existing record with existing cluster ID I catch NullReferenceException
in

    public class OLoadRecord
    {
      .....
        public ODocument Run()
        {
            var operation = new LoadRecord(_orid, _fetchPlan, _connection.Database);
            var result = new OCommandResult(_connection.ExecuteOperation(operation));
            return result.ToSingle().To<ODocument>(); --< THIS STRING
        }

Because result is Empty. In this method

    public class OCommandResult
    {
        ...
        public ODocument ToSingle()
        {
            ODocument document = null;
            // IN THIS PLACE WE GET PayloadStatus.NoRemainingRecords
            switch (_document.GetField<PayloadStatus>("PayloadStatus"))
            {
                case PayloadStatus.SingleRecord:
                    document = _document.GetField<ODocument>("Content");
                    break;
                case PayloadStatus.RecordCollection:
                    document = _document.GetField<List<ODocument>>("Content").FirstOrDefault();
                    break;
                case PayloadStatus.SerializedResult:
                    document = new ODocument();
                    document.SetField<object>("value",_document.GetField<object>("Content"));
                    break;
                default:
                    break;
            }

            return document;
        }

I've traced the error and noticed that in Receive() method we give Status == ResponseStatus.OK but not ERROR.

    internal class Response
    {
        public void Receive()
        {
            Reader = new BinaryReader(Connection.GetNetworkStream());
            var reader = Reader;
            Status = (ResponseStatus)reader.ReadByte();
            SessionId = reader.ReadInt32EndianAware();

            //if (Connection.UseTokenBasedSession && Connection.ProtocolVersion > 26)
            //{
            //    var size = reader.ReadInt32EndianAware();
            //    Token = reader.ReadBytesRequired(size);
            //}

            if (Status == ResponseStatus.ERROR)
            {

DB: OrientDB v2.2.3 Enterprise
Windows 8.1
Visual Studio 2015.
Server Config and my db in archive
[live_rsm_service.gz](https://github.com/orientechnologies/OrientDB-NET.binary/files/334791/live_rsm_service.gz)
[orientdb-server-config.zip](https://github.com/orientechnologies/OrientDB-NET.binary/files/334792/orientdb-server-config.zip)

The database has been created by this binary client.

**Comment by GrayDelacluyse** [comment]
@aligin Nice investigation, I believe this would actually be a OrientDB issue and not the client since Error should be returned from the DB.

You would need to open a issue here
https://github.com/orientechnologies/orientdb
