### ISSUE TITLE
Adding a LINQ provider to this project

### ISSUE THREAD

**Issue by samirski** [orientechnologies/OrientDB-NET.binary#111]
Hi there. First of all thank you for not abandoning the project and making it OrientDB 2.2 compatible. While the approach does allow the developers to interact with OrientDB from .Net code I think the overall usage and the experience will greatly improve is this implementation would have a LINQ provider implemented. This is more or less the standard this days when some sort of interaction with a database is required. I think a good start would be to look at the re-linq project (https://relinq.codeplex.com). Here is a good example on how the ArangoDB .Net Client is implemented: http://www.arangoclient.net.

**Comment by GrayDelacluyse** [comment]
Hi @samirski, we appreciate the feedback.  Since adopting the client we have considered many different directions and approaches to take and value the input from the community on what they would like to see.

**Comment by samirski** [comment]
Hi @GrayDelacluyse, the issue I see here is fact that OrientDB is not really known among the .net developers. So it's like chicken or the egg problem. To get the feedback, the usage needs to be higher, but to increase the usage, a nicely implemented solution is needed first. Maybe you should distribute a survey or write a blog post on the ideas and see what happens next. This is just a suggestion.

**Comment by GrayDelacluyse** [comment]
@samirski We fully support pull request, I would love to see a base implementation.
