### ISSUE TITLE
Error when using .NET driver

### ISSUE THREAD

**Issue by alextobias48** [orientechnologies/OrientDB-NET.binary#113]
I'm having issues getting the .NET driver to connect to a server running orientdb. I followed the instructions in the wiki and I get the error: "Requested value 'none' was not found".

I read somewhere that this error is because the NuGet package for this project isn't up to date. Will the NuGet package be updated any time soon? Or is there another way to use this driver?

Thanks!

**Comment by GrayDelacluyse** [comment]
Hi @alextobias48 

The Nuget package is fully up to date with the repo.

I would be happy to try and help figure out the issue is.  Can you give more information on where the error occurs and the full details with errors.

Thanks,
Gray
