### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hosseinGanjyar** [orientechnologies/OrientDB-NET.binary#124]
I need a documentation for implement orientdb in c#, but don't find any document for this issue.
thanks

**Comment by lvca** [comment]
@tglman could you help @hosseinGanjyar on this?

**Comment by aoighost** [comment]
This is blocking my use of this for implementation as well.

**Comment by lukasmerta** [comment]
at least some docs are in old repo wiki
https://github.com/yojimbo87/OrientDB-NET.binary/wiki
some use cases are also in Test
https://github.com/orientechnologies/OrientDB-NET.binary/tree/master/src/Orient.Nunit.Test
but yes, there is no documentation on official pages and there are also missing comments on public interface so it's very hard to start using this DB (native "so called" official supported driver) from .NET

**Comment by GrayDelacluyse** [comment]
Thank you for the feedback.  The wiki from yojimbo87 is out of date and no longer in sync with the office repository.  However, we happily support pull request from the community as the driver is an open source project.  Please feel free to contribute.
