### ISSUE TITLE
How do we execute a server function?

### ISSUE THREAD

**Issue by snarlynarwhal** [orientechnologies/OrientDB-NET.binary#131]
I found the [Functions documentation](http://orientdb.com/docs/2.0/orientdb.wiki/Functions.html) and read the Usage via Java API section, but could not find the equivalent functions in the C# API. :(

**Comment by GrayDelacluyse** [comment]
You should be able to execute the function inside a standard query instead.

**Comment by snarlynarwhal** [comment]
How do I do that? Can't seem to find documentation for executing a function via sql.

**Comment by GrayDelacluyse** [comment]
Select functionName()
