### ISSUE TITLE
Using fetchplans to build nested tree objects in .Net

### ISSUE THREAD

**Issue by sharper89** [orientechnologies/OrientDB-NET.binary#132]
Hello,
i read that you can using fetchplans to build nested tree objects with query.

This is my graph. I use a _traverse_ to get my structure.

![image](https://cloud.githubusercontent.com/assets/26001485/23298766/2fe3d8ac-fa7f-11e6-90a2-9f4b6bfe088c.png)

Now I have tried the following code:

` var oDoc = db.Query<ODocument>("traverse * from(select from ProjectStructure WHERE StrucId = 'F8E2E8F4-06BE-48E0-BF4A-0E7B0B3629FA')", "*:-1");`

The result of this is the following list but **no** nested tree objects.

![image](https://cloud.githubusercontent.com/assets/26001485/23298970/0307d120-fa80-11e6-9a0b-91f4377ac947.png)

What am I doing wrong ? 
My requirement is similar to this post in [stackoverflow.com](http://stackoverflow.com/questions/33813257/in-orientdb-how-do-i-get-all-verticies-as-json-and-exclude-edges-in-results
)

**Comment by GrayDelacluyse** [comment]
Currently the driver will not return nested ODoc objects, you would have to rebuild the tree from the included metadata
