### ISSUE TITLE
Incorrect Protocol Version

### ISSUE THREAD

**Issue by josephthomas3012** [orientechnologies/OrientDB-NET.binary#140]
Hello

using orient db .net driver , when i try to connect to the db , i get exception "Incorrect Protocol Version", 
`   OClient.ProtocolVersion = ProtocolVersion = BinarySerializer.ToShort(_readBuffer.Take(2).ToArray());`
here the buffer will have no data, and the ProtocolVersion will be 0.
```
 if (ProtocolVersion <= 0)
 throw new OException(OExceptionType.Connection, "Incorect Protocol Version " + ProtocolVersion);
```
Regards

**Comment by SchroterQuentin** [comment]
Hello,
I have the same issue and my mistake was I was using the wrong port number. 2424 is the good one if I remember well.
Regards

**Comment by josephthomas3012** [comment]
Hello SchroterQuentin 
Thanks for the reply.
```
<listener protocol="binary" socket="default" port-range="2424-2430" ip-address="0.0.0.0"/>
<listener protocol="http" socket="default" port-range="2480-2490" ip-address="0.0.0.0">
```

2424 is related to binary , even if i set the port to 2424 on http socket setting , i get the same error.
could you please share any other settings, details, so as i can fix this error.

Regards

**Comment by SchroterQuentin** [comment]
Hello,
If you want to use the driver in C# to connect to the database, you have to use the binary port, it is the port used to communicate. The http port is used fort REST request and web ui.

**Comment by josephthomas3012** [comment]
Hello

But when i try to access interface of orient Db with 2424 port i get this error, 
```
com.orientechnologies.common.io.OIOException: Impossible to read a chunk of 
length:541611092 max allowed chunk length:16777216 see 
NETWORK_BINARY_MAX_CONTENT_LENGTH settings
```
and when i try to access with the driver i get

`An exception of type 'System.OutOfMemoryException' occurred in mscorlib.dll but was not handled in user code`

Regards

**Comment by SchroterQuentin** [comment]
That's better, now it seems that it's known issue : https://github.com/orientechnologies/orientdb/issues/6311

Check what version of OrientDB you have and what kind of database you choose, if you can't solve it please use a docker image which default parameter.

**Comment by josephthomas3012** [comment]
i was using orientdb-community-2.2.20, and now i moved  to orientdb-community-2.2.22 , to my surprise, it started working :)
 Thanks SchroterQuentin for helping me out on this.
