### ISSUE TITLE
Further development

### ISSUE THREAD

**Issue by tomazk8** [orientechnologies/OrientDB-NET.binary#162]
For 2 years now, there was no update to this client and it was also removed from NuGet. May I ask why? I want to use OrientDB 3.0.x but the binary protocol was changed and requires handshake after opening the connection. Is there a plan to continue the development of this client?

Thanks

**Comment by lvca** [comment]
Hi @tomazk8, we adopted the driver 2 months ago and now we have developers that are working to release v3.0 soon.
