### ISSUE TITLE
Change this repo to normal instead of a fork.

### ISSUE THREAD

**Issue by poindextrose** [orientechnologies/OrientDB-NET.binary#18]
Github doesn't index forked repos for search and it would be nice to search this repo on Github. Since this fork is now the official C# client it seems appropriate to break the dependency to workshare/OrientDB-NET.binary by converting it to a normal repo.

**Comment by GoorMoon** [comment]
@lvca could this be done ?

**Comment by poindextrose** [comment]
An additional benefit is that the wiki will be easy to maintain. I would like to help update the wiki.

**Comment by jiujiu1123** [comment]
+1

**Comment by lvca** [comment]
@rwg0 the only way is deleting your repository under "workshare". Can you do that?

**Comment by poindextrose** [comment]
An answer on Stackoverflow: [Delete fork dependency of a GitHub repository](http://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository) says that a repo can be converted by contacting [Github Support](https://github.com/contact).

**Comment by lvca** [comment]
@poindextrose thanks, email sent.

**Comment by lvca** [comment]
Wow, already detached: they were super fast!
