### ISSUE TITLE
BaseOperation.EndOfStream() fails with NPE on Mono

### ISSUE THREAD

**Issue by poindextrose** [orientechnologies/OrientDB-NET.binary#19]
@GoorMoon 

The `EndOfStream` method was introduced in commit 72b9244a01be56af08a9440fda65fdf6cb563ca3 but the `GetField` method returns null when running on Mono.

If I change EndOfStream to always return false, then all the tests pass on Mono when connecting to OrientDB 2.0. 

I've tried to duplicate the logic with Mono but so far haven't been able to. Before I dig into it more please help me understand why EndOfStream is needed. The simplest fix I know of right now is to detect if Mono is the runtime and just return false. Please advise.

**Comment by GoorMoon** [comment]
EndOfStream is workaround (I don't like him) about bug exist in OrientDB version less than 2.0.
Response is different if storage type is memory or plocal.

**Comment by poindextrose** [comment]
That explains why the tests were changed from memory to plocal. I tried the tests with memory. I'll see what I can do for reproducing the logic in Mono.

**Comment by GoorMoon** [comment]
Hey i don't have Mono, but seeking on internet and found following article about NonPublic Fields and inheritance

http://www.netdataobjects.com/Portal/NDORunsUnderMono/tabid/94/Default.aspx


1. If you search for private fields using Reflection, Microsoft .NET automatically adds the Flag DeclaredOnly to the BindingFlag NonPublic. That way, if you use NonPublic, you get only the private fields of the current type, not the inherited private fields of the base classes -- which is the case in Mono. To make the code working equal in Microsoft .NET and Mono, you always have to add the flag DeclaredOnly, if you use NonPublic. If you want to get private fields of the base types of your types, you have to iterate through the whole inheritance chain.

**Comment by poindextrose** [comment]
Thanks for the information. It looks like Mono doesn't have the private fields that `EndOfStream()` is looking for. I notice that for the OrientDB 2.0 (which appears to use ProtocolVersion 28), the problem that `EndOfStream()` solves is not present (on my machine). I've updated the pull request to skip the `EndOfStream()` test for ProtocolVersion 28 or greater. Hopefully this is also valid on .NET.

**Comment by GoorMoon** [comment]
Yes this is valid on version 2.0 protocol is same for both storage types.
