### ISSUE TITLE
A number of common data type not supported

### ISSUE THREAD

**Issue by gohsianghwee** [orientechnologies/OrientDB-NET.binary#23]
Hi,

I have done some testing on the insert but I encountered number of issues and would like to lodge a reports. 

1. GUID is not supported and will throw error.
2. Enum type also not supported.
3. IList is not supported
4. Dictionary and SortedList is not supported
5. List<Object> is also not supported

Apart from the issues listed. The data type is not similar and the figure had been rounded up as well. Attached here with the screenshot and the original source code.

![snapshot1](https://cloud.githubusercontent.com/assets/4898171/5920206/a5c588b4-a675-11e4-955d-50815a2dfc33.png)
![snapshot2](https://cloud.githubusercontent.com/assets/4898171/5920207/a60fdd2e-a675-11e4-806a-db6d7410d3cf.png)

public static void TestOrientDBObjectTypeSupported()
        {
            var GlobalTestDatabaseName = "TestDatabaseName";
            var GlobalTestDatabaseType = ODatabaseType.Graph;
            var GlobalTestDatabaseAlias = "TestDatabaseNameAlias";

            _server = new OServer(_hostname, _port, _rootUserName, _rootUserParssword);
            //if (_server.DatabaseExist(GlobalTestDatabaseName, OStorageType.PLocal))
            //{
            //    _server.DropDatabase(GlobalTestDatabaseName, OStorageType.PLocal);
            //}

            //_server.CreateDatabase(GlobalTestDatabaseName, GlobalTestDatabaseType, OStorageType.PLocal);
            OClient.CreateDatabasePool(
                _hostname,
                _port,
                GlobalTestDatabaseName,
                GlobalTestDatabaseType,
                _username,
                _password,
                10,
                GlobalTestDatabaseAlias
            );
            DateTime startTime = DateTime.Now;
            Console.WriteLine("Start Time: " + startTime.ToLongTimeString());

            using (ODatabase database = new ODatabase("TestDatabaseNameAlias"))
            {
                var employee = new DemoEmployee();
                employee.Name = "Janet";
                employee.Age = 33;
                employee.SomeVeryLongNumber = 12345678901234567;
                employee.BirthDate = new DateTime(2015, 1, 24, 2,2,2);
                employee.Salary = (decimal)23434.1234567891;
                employee.Commission = (double)23434.1234567891;
                employee.Allowance = (float)3434.1234567891;
                employee.IsMarried = true;
                employee.SomeIntegerList = new List<int>();
                employee.SomeIntegerList.Add(1);
                employee.SomeIntegerList.Add(2);
                employee.SomeIntegerList.Add(3);
                employee.SomeIntegerArrayList = new int[3] { 4, 2, 3 };
                employee.SomeDecimalList = new List<decimal>();
                employee.SomeDecimalList.Add((decimal)23434.1234567891);
                employee.SomeDecomeArray = new decimal[3] { (decimal)23434.1234567890, (decimal)23434.1234567890, (decimal)23434.1234567890 };
                employee.Kids = new List<DemoChild>();
                var kid = new DemoChild();
                kid.Name = "Janet";
                kid.Age = 33;
                kid.SomeVeryLongNumber = 12345678901234567;
                kid.BirthDate = new DateTime(2015, 1, 24, 2, 2, 2);
                kid.Salary = (decimal)23434.1234567891;
                kid.Commission = (double)23434.1234567891;
                kid.Allowance = (float)3434.1234567891;
                kid.IsMarried = true;
                kid.SomeIntegerList = new List<int>();
                kid.SomeIntegerList.Add(1);
                kid.SomeIntegerList.Add(2);
                kid.SomeIntegerList.Add(3);
                kid.SomeIntegerArrayList = new int[3] { 4, 2, 3 };
                kid.SomeDecimalList = new List<decimal>();
                kid.SomeDecimalList.Add((decimal)23434.1234567891);
                kid.SomeDecomeArray = new decimal[3] { (decimal)23434.1234567890, (decimal)23434.1234567890, (decimal)23434.1234567890 };
                employee.Kids.Add(kid);
                //employee.SomeIListInteger = new List<int>();
                //employee.MyKeyValues = new Dictionary<int, string>();
                //employee.MyKeyValues.Add(1, "Name");
                //employee.SomeIListInteger.Add(7);
                database.Insert<DemoEmployee>(employee).Run();
            }

            DateTime endTime = DateTime.Now;
            TimeSpan duration = endTime - startTime;
            Console.WriteLine("End Time: " + endTime.ToLongTimeString());
            Console.WriteLine("Total time taken: " + duration.TotalSeconds);
        }

 public class DemoChild
    {
        public string Name { get; set; }

        public int Age { get; set; }

        public long SomeVeryLongNumber { get; set; }

        public decimal Salary { get; set; }

        public double Commission { get; set; }

        public float Allowance { get; set; }

        public DateTime BirthDate { get; set; }

        public bool IsMarried { get; set; }

        public List<int> SomeIntegerList { get; set; }

        public int[] SomeIntegerArrayList { get; set; }

        public List<decimal> SomeDecimalList { get; set; }

        public decimal[] SomeDecomeArray { get; set; }
    }

    public class DemoEmployee
    {
        //public Guid SomeOtherId { get; set; }

        public string Name { get; set; }

        public int Age { get; set; }

        public long SomeVeryLongNumber { get; set; }
        
        public decimal Salary { get; set; }

        public double Commission { get; set; }

        public float Allowance { get; set; }

        public DateTime BirthDate { get; set; }

        public bool IsMarried { get; set; }

        public List<int> SomeIntegerList { get; set; }

        public int[] SomeIntegerArrayList { get; set; }

        public List<decimal> SomeDecimalList { get; set; }

        public decimal[] SomeDecomeArray { get; set; }

        public List<DemoChild> Kids { get; set; }
        //public IList<int> SomeIListInteger { get; set; }

        //public Dictionary<int, string> MyKeyValues { get; set; }

        // public Color MyFavoriteColor { get; set; }
        //public enum Color
        //{
        //    Blue, Red
        //}
    }

**Comment by GoorMoon** [comment]
@gohsianghwee
GUID saved as string in database,
ENUM saved as string in database
WHDYT

**Comment by gohsianghwee** [comment]
Hi GoorMoon,

I agree with you that GUID may be able to stored as string though it would be good if it can be handled by the driver, however, I feel Enum serialization should be handled by .Net driver itself. What is WHDYT by the way?


Cordially,
Goh

**Comment by GoorMoon** [comment]
Hi,
of course it would be handled by the driver,  I ask you what do you think to store such types as a string in the database?

**Comment by gohsianghwee** [comment]
HI Goormoon,

I have no problem if the data will be stored as string in the OrientDB eventually. So long the .Net driver can serialize and deserialize it automatically, developers will have less job to do the conversion in manual.

**Comment by GoorMoon** [comment]
@gohsianghwee,
Could you check again ?

**Comment by gohsianghwee** [comment]
Ho GoorMoon,

Thanks. It's working now but with little problems. The property for SomeVeryLongNumber value is 12345678901234567 but it was stored as 12345678901234568. The other problem is the Salary is decimal type but at the end stored as double. I am ok with that as the figure is exactly the same. That maybe because of the .Net type and OrientDB type are different. However, Allowance is float type 3434.1234567891 and when it was stored it ended up 3434.124 float type. I would suggest to store it as double instead as developer won't aware of the problem.

By the way, where shall I post OrientDB related question especially on performance on querying. I tried to post it here http://stackoverflow.com/questions/28205406/orientdb-slow-query-performance but seems like no one reply. Could you shed a light? Thanks.

**Comment by GoorMoon** [comment]
Hi @gohsianghwee ,
orientdb-studio has a bug not show correct type,
orientdb has a bug can't store decimal values [#3483](https://github.com/orientechnologies/orientdb/issues/3483).
Have some issues with float type numbers that rounded on the orientdb side.
store float type as double can cause some conversion problem on the driver side.

OrienDB community has excellent user group https://groups.google.com/forum/#!forum/orient-database where you can post questions

**Comment by gohsianghwee** [comment]
Hi GoorMoon,

Noted with thanks. May I suggest if this is the case all the .Net type on float and decimal store as double type in OrientDB instead. As I find it the most accurate of all.

I will have report my performance issue to google group instead. Thanks again for your support.

**Comment by GoorMoon** [comment]
@poindextrose ,

WDYT about using double as replacement for (float,decimal) ?

**Comment by gohsianghwee** [comment]
Do you mean .Net type using double? That's hard because float and double type always give a wrong answer for normal financial computation. It's more suitable for scientific computation.

However, I think it is good if the type is stored as double in OrientDB. So long it can be deserialized back
to .Net as decimal type.

**Comment by GoorMoon** [comment]
@gohsianghwee ,
I just tried this and still has issues with DataType conversion from .Net to the OrientDB.
I better would keep this issue open and try to work with orientdb team to fix this issue.

**Comment by gohsianghwee** [comment]
GoorMoon,

Noted with thanks. I shall proceed on the other part of testing instead

**Comment by poindextrose** [comment]
@GoorMoon 

I recommend that we use a custom `BigDecimal` implementation for the OrientDB decimal type because OrientDB is using `java.math.BigDecimal`. [Here is one I found](https://gist.github.com/nberardi/2667136), but I haven't evaluated it fully.

I also recommend that we map .NET float to OrientDB float and .NET double to OrientDB double. I've been looking at the broken test case and I'm trying to figure out why the rounding error is happening on the float.

**Comment by GoorMoon** [comment]
@poindextrose ,
I think you are right, we need to use our custom types for all OrientDB types and not only for Big Decimal. For this we must re-wright driver.

**Comment by poindextrose** [comment]
What other types do you think we need to handle as a special case? I think BigDecimal is the only real problem. As a start, we could map C# string to OrientDB BigDecimal and let the user convert the string to their own BigDecimal implementation if needed or let them convert it themselves to C# decimal if the precision loss is acceptable.

I have some ideas for translating the Link* types which I'd like to discuss soon.

**Comment by GoorMoon** [comment]
I think we need abstraction over all orientdb types in that case driver will be more stable to the features changes in the orientdb side.
Today we not support RidBag and that why we have problem in links.
I think who use driver with oriendb should be aware of warriors orientdb types and complex cases.

What ideas you have about Links ?

**Comment by gohsianghwee** [comment]
Hi GoorMoon,

I figure out some problem with Sorted List type. It will throws error whenever there is a property for sorted list type being inserted. Would you mind to check on this? Thanks.

Cordially,
Goh

**Comment by GoorMoon** [comment]
@gohsianghwee ,

Sure, do you have some test case for this ?

**Comment by gohsianghwee** [comment]
Hi GoorMoon,

Here you go!
public static void TestOrientDBObjectTypeSupported()
        {
            var GlobalTestDatabaseName = "TestDatabaseNameAlias";
            var GlobalTestDatabaseType = ODatabaseType.Graph;
            var GlobalTestDatabaseAlias = "TestDatabaseNameAlias";
            
            _server = new OServer(_hostname, _port, _rootUserName, _rootUserParssword);
            if (_server.DatabaseExist(GlobalTestDatabaseName, OStorageType.PLocal))
            {
                _server.DropDatabase(GlobalTestDatabaseName, OStorageType.PLocal);
                
            }

            _server.CreateDatabase(GlobalTestDatabaseName, GlobalTestDatabaseType, OStorageType.PLocal);

            OClient.CreateDatabasePool(
                _hostname,
                _port,
                GlobalTestDatabaseName,
                GlobalTestDatabaseType,
                _username,
                _password,
                10,
                GlobalTestDatabaseAlias
            );
            DateTime startTime = DateTime.Now;
            Console.WriteLine("Start Time: " + startTime.ToLongTimeString());

            using (ODatabase database = new ODatabase(GlobalTestDatabaseName))
            {
                database.Create.Class<DemoEmployee>().Run();
                
                for (int index = 1; index <= 10; index++)
                {
                    var employee = new DemoEmployee();
                    employee.SomeOtherId = Guid.NewGuid();
                    employee.Name = "Janet";
                    employee.Age = index;
                    employee.SomeVeryLongNumber = 12345678901234567;
                    employee.BirthDate = new DateTime(2015, 1, 24, 2, 2, 2);
                    employee.Salary = (decimal)(3000 + (index * 3));
                    employee.Commission = (double)23434.1234567891;
                    employee.Allowance = (float)3434.1234567891;
                    employee.IsMarried = true;
                    employee.SomeIntegerList = new List<int>();
                    employee.SomeIntegerList.Add(1);
                    employee.SomeIntegerList.Add(2);
                    employee.SomeIntegerList.Add(3);
                    employee.SomeIntegerArrayList = new int[3] { 4, 2, 3 };
                    employee.SomeDecimalList = new List<decimal>();
                    employee.SomeDecimalList.Add((decimal)23434.1234567891);
                    employee.SomeDecomeArray = new decimal[3] { (decimal)23434.1234567890, (decimal)23434.1234567890, (decimal)23434.1234567890 };
                    employee.YearlyAchievement = new SortedList<int, string>();
                    employee.YearlyAchievement.Add(2014, "Best Employee Award");
                    employee.YearlyAchievement.Add(2015, "Best Potential Employee Award");
                    
                    employee.Kids = new List<DemoChild>();
                    var kid = new DemoChild();
                    kid.Name = "Janet";
                    kid.Age = 33;
                    kid.SomeVeryLongNumber = 12345678901234567;
                    kid.BirthDate = new DateTime(2015, 1, 24, 2, 2, 2);
                    kid.Salary = 3000 + (index * 10);
                    kid.Commission = (double)23434.1234567891;
                    kid.Allowance = (float)3434.1234567891;
                    kid.IsMarried = true;
                    kid.SomeIntegerList = new List<int>();
                    kid.SomeIntegerList.Add(1);
                    kid.SomeIntegerList.Add(2);
                    kid.SomeIntegerList.Add(3);
                    kid.SomeIntegerArrayList = new int[3] { 4, 2, 3 };
                    kid.SomeDecimalList = new List<decimal>();
                    kid.SomeDecimalList.Add((decimal)23434.1234567891);
                    kid.SomeDecomeArray = new decimal[3] { (decimal)23434.1234567890, (decimal)23434.1234567890, (decimal)23434.1234567890 };

                    employee.Kids.Add(kid);
                    employee.SomeIListInteger = new List<int>();
                    employee.MyKeyValues = new Dictionary<int, string>();
                    employee.MyKeyValues.Add(1, "Name");
                    employee.SomeIListInteger.Add(7);
                    employee.SomeIListInteger.Add(8);
                    database.Insert<DemoEmployee>(employee).Run();
                }
            }



            DateTime endTime = DateTime.Now;
            TimeSpan duration = endTime - startTime;
            Console.WriteLine("End Time: " + endTime.ToLongTimeString());
            Console.WriteLine("Total time taken: " + duration.TotalSeconds);
        }

public class DemoEmployee : AggregateRoot
    {
        public Guid SomeOtherId { get; set; }

        public string Name { get; set; }

        public int Age { get; set; }

        public long SomeVeryLongNumber { get; set; }
        
        public decimal Salary { get; set; }

        public double Commission { get; set; }

        public float Allowance { get; set; }

        public DateTime BirthDate { get; set; }

        public bool IsMarried { get; set; }

        public List<int> SomeIntegerList { get; set; }

        public int[] SomeIntegerArrayList { get; set; }

        public List<decimal> SomeDecimalList { get; set; }

        public decimal[] SomeDecomeArray { get; set; }

        public List<DemoChild> Kids { get; set; }
        public IList<int> SomeIListInteger { get; set; }

        public Dictionary<int, string> MyKeyValues { get; set; }

        public SortedList<int, string> YearlyAchievement { get; set; }

        public Color MyFavoriteColor { get; set; }
        public enum Color
        {
            Blue, Red
        }
    }

**Comment by cwaldron** [comment]
Why is Guid stored as a string and not a 16-byte binary value?

**Comment by GoorMoon** [comment]
to support compatibility with other drivers.
