### ISSUE TITLE
Should fetch linked document

### ISSUE THREAD

**Issue by poindextrose** [orientechnologies/OrientDB-NET.binary#26]
A query with a fetchplan does not properly fetch linked documents. Instead only the ORID is retrieved.

I'll submit a test case.

**Comment by poindextrose** [comment]
I've looked into this some more. It looks like the server isn't returning any pre-fetched records from `ODatabase.Query()` or `Odatabase.Command()` when fetchPlan is specified. I can see the fetchplan is making it to the server from the binary protocol logs. Is this possibly a bug in the server?

**Comment by GoorMoon** [comment]
I need to look more, maybe i am not using REQUEST_COMMAND correct
https://github.com/orientechnologies/orientdb/wiki/Network-Binary-Protocol#request_command
https://github.com/orientechnologies/orientdb/wiki/Network-Binary-Protocol-Commands

**Comment by GoorMoon** [comment]
On second thought, you have created a linked document and represents embedded test case so it does not we will establish.
I fixed the test case in such a way that you see through the use of linked documents

**Comment by poindextrose** [comment]
Thanks! I totally missed the `ClientCache` Well at least now we have a test case that covers `ClientCache`
