### ISSUE TITLE
How to check if the class has already exist?

### ISSUE THREAD

**Issue by gohsianghwee** [orientechnologies/OrientDB-NET.binary#34]
Hi,

I couldn't find the is class exist method. May I know how to check the existence of the class? Thanks.

Cordially,
Goh

**Comment by GoorMoon** [comment]
@gohsianghwee ,

if(database.Schema.GetClustersForClass("TestClass")!=null)
{
	// TODO: Class exists
}

**Comment by gohsianghwee** [comment]
Hi GoorMoon,

Thanks for your helping hand. I did come across the method but thought that was the function to get list of clusters and might throw error if I call it.

**Comment by gohsianghwee** [comment]
By the way, I would suggest to have a method as below. What do you think?

public bool IsClassExist(string className)

**Comment by GoorMoon** [comment]
cool

**Comment by gohsianghwee** [comment]
Hi GoorMoon,

I want to make some changes on this and there is also another method I would like to have such as 
Create.Class<T>("someOtherClassName"). Currently I figure out there is no way I can pass the Generic Type with the class name I would like to have. I think this is important feature for me as I might store the same object but with different class name. Do you think I shall fork it as another project or you would like to share the write access for this repository to me? Thanks.

**Comment by GoorMoon** [comment]
Hi @gohsianghwee,

I am not owner of this repository and can't give you write access.
You should fork this repository and provide PR request i will investigate
this and merge them to the master branch.

Your suggestion is very interesting.

Best Regards,
Roman Gordon

**Comment by gohsianghwee** [comment]
Hi Roman,

Certainly. I shall fork this repository instead. Thanks.
