### ISSUE TITLE
  Single quote escape convention

### ISSUE THREAD

**Issue by bnoffer** [orientechnologies/OrientDB-NET.binary#38]
Related to:

https://github.com/orientechnologies/orientdb/issues/1275

Just came across the issue with single quotes while importing data using the .NET Driver from another DBMS to OrientDB. The occurrence of single quotes in strings lead to parsing errors. I manually used the \\\' convention to replace the single quotes, but this should be handled by the driver.

**Comment by GoorMoon** [comment]
@bnoffer,
Do you have a test case ?

**Comment by cocogorilla** [comment]
Provided class:
    public class Test
    {
        public string SomeString { get; set; }
    }
The following throws illegal character at position 41:
        [Fact]
        public void CannotPerformInjection()
        {
            using (var db = new ODatabase(Dbname))
            {
                if (!db.Schema.IsClassExist<Test>())
                {
                    db.Create.Class<Test>().CreateProperties<Test>().Run();
                }

                db.Command("delete from Test");

                var text = @"Jim'n";
                var test = new Test() { SomeString = text };
                db.Insert(test).Run();

                var result = db.Select().From<Test>().ToList<Test>();
                Assert.Equal(text, result.Single().SomeString);
            }
        }

**Comment by bnoffer** [comment]
Thank you @cocogorilla for providing the Test.
