### ISSUE TITLE
prepared sql

### ISSUE THREAD

**Issue by cocogorilla** [orientechnologies/OrientDB-NET.binary#42]
According to this post, prepared sql is supported:
https://groups.google.com/forum/#!msg/orient-database/sytdxVTwk_w/zAR12xjZlhUJ

Can this be supported through the .NET client?

**Comment by GoorMoon** [comment]
Using example look at TestCase `PreparedQueryTest.cs`

**Comment by jiujiu1123** [comment]
@GoorMoon Is there a way of using prepared sql for creating document?

**Comment by GoorMoon** [comment]
No, open issue please i will implement this
