### ISSUE TITLE
OrientDB Server Accepts Connection Does Not Respond to Connect request

### ISSUE THREAD

**Issue by billbshs** [orientechnologies/OrientDB-NET.binary#44]
Running latest, attempt to run either console or any unit test OrientDB server never responds to connection request, causing client to hang indefinitely waiting for a response:

Connection.cs Line 248
Document = ExecuteOperation(operation);

Inbound socket connection is created, but the server never responds.

**Comment by billbshs** [comment]
Nevermind, master doesn't support protocol 28, which causes the connection to hang.

**Comment by GoorMoon** [comment]
@billbshs ,
Pushed protocol28 branch to the master.
Now driver support tokenBased session
