### ISSUE TITLE
Anyway to get all the classes name in the database

### ISSUE THREAD

**Issue by gohsianghwee** [orientechnologies/OrientDB-NET.binary#56]
Hi,

Is there anyway for us to get all the classes available in the database?

Cordially,
Goh

**Comment by amgiorgi** [comment]
Is this what you are lookign for?
 
IEnumerable<string> listaClasses = db.Schema.Classes();

**Comment by gohsianghwee** [comment]
Hi @GoorMoon ,

Thanks. This is exactly what I want.
