### ISSUE TITLE
driver not fetching @fieldTypes 

### ISSUE THREAD

**Issue by amgiorgi** [orientechnologies/OrientDB-NET.binary#57]
Here is what I have done so far to try and debug retrieved values:

document = db.Query("select from interventi limit 10");

                foreach (ODocument singleDoc in document)
                {
                    List<ORID> orids = singleDoc.GetField<List<ORID>>("out_InterventoICD");
                    foreach(ORID rid in orids)
                    {
                        lblResults.Text += rid.ToString() + ",";
                    }
                    lblResults.Text += "<br />";

                    string relationTypes =  singleDoc.GetField<string>("@fieldTypes");

                    lblResults.Text += relationTypes;

                }

If I use REST protocol I can retrieve the list of fields with related type correctly but the binary driver instead seems to not return any value. From REST response it looks like @fieldTypes should be a string. I have anyway tried to retrieve it the following way to no avail.

List<string> relationTypes =  singleDoc.GetField<List<string>>("@fieldTypes");

Being @fieldTypes a special internal field such as ORID, OType, OVersion, I would expect a specific method in the driver to retrieve it but it doesn't seem to exist.

Am I missing something?

**Comment by GoorMoon** [comment]
@amgiorgi ,
Are you using latest code ?

REST and BINARY protocol are different and in the rest protocol you get some type hints in the binary protocol types is defined by result.

I don't understand your issue from description you provide.

Can you provide some test-case for issue.

**Comment by amgiorgi** [comment]
Well, I was basing my assumption on the REST protocol and expecting the same (or similar) response from the binary one.
Are you saying that the @fieldTypes property is not available/supported in the binary protocol?

**Comment by GoorMoon** [comment]
Binary protocol is strong typed look here http://www.orientechnologies.com/docs/last/orientdb.wiki/Record-CSV-Serialization.html

**Comment by GoorMoon** [comment]
If you use strong schema for the class you can get properties by queering
database.Schema.Properties("<classname>")

**Comment by amgiorgi** [comment]
HI @GoorMoon, thank you for your prompt reply.
Yes I know that bynary protocol is strongly typed but nevertheless in my POCO there are no properties related to OrientDB internal properties. I am using the graph model and in design Studio I noticed that outgoing and incoming edges are comfortably marked as out_NameOfRelation or in_NameOfRelation.
Incidentally, using the REST protocol I also found out that I could use the @fieldTypes property in order to find out which relations I had to a specific class, instead of hard coding any possible class/edge relation in the code. 
Mine was just a workaround as I have not found a way to identify which edges I have in() and out() to a specific class.
Kindly elaborate some more on the database.Schema.Properties() method. I haven't used it yet and perhaps it will solve my problem.
 An another question, what if I am not using a common schema for all documents? Using REST protocol I could again use @fieldTypes to identify the presence of odd linkSets available in some documents but not in all documents and get them by linkset_name=Z.
How do I achieve that with the binary driver?

Thank you for your help

**Comment by GoorMoon** [comment]
If i understand well you question (sorry my bad English)

In binary driver you have strong Type

something like that

```c#
       class Widget
        {
            public int Value { get; set; }
            public List<ORID> out_VersionOf { get; set; }
        }

        class WidgetVersion
        {
            public int Value { get; set; }
            public HashSet<ORID> in_VersionOf { get; set; }

        }
       public void testMethod()
       {
            using (TestDatabaseContext testContext = new TestDatabaseContext())
            using (ODatabase database = new ODatabase(TestConnection.GlobalTestDatabaseAlias))
            {
                database.Command("alter database custom useLightweightEdges=false");

                database.Create.Class<Widget>().Extends("V").CreateProperties().Run();
                database.Create.Class<WidgetVersion>().Extends("V").CreateProperties().Run();

                database.Create.Class("VersionOf").Extends("E").Run();

                var w1 = new Widget() { Value = 12 };
                var wv1 = new WidgetVersion() { Value = 23 };
                var wv2 = new WidgetVersion() { Value = 34 };

                var v1 = database.Create.Vertex(w1).Run();
                var v2 = database.Create.Vertex(wv1).Run();
                var v3 = database.Create.Vertex(wv2).Run();

                var e1 = database.Create.Edge("VersionOf").From(v1).To(v2).Run();
                var e2 = database.Create.Edge("VersionOf").From(v1).To(v3).Run();

                var loaded1 = database.Load.ORID(v1.ORID).Run<Widget>();
                Assert.AreEqual(2, loaded1.out_VersionOf.Count);
                Assert.IsTrue(loaded1.out_VersionOf.Contains(e1.ORID));
                Assert.IsTrue(loaded1.out_VersionOf.Contains(e2.ORID));
                Assert.AreEqual(12, loaded1.Value);

                var loaded2 = database.Load.ORID(v2.ORID).Run<WidgetVersion>();
                Assert.IsNotNull(loaded2.in_VersionOf);
                Assert.AreEqual(1, loaded2.in_VersionOf.Count);
                Assert.AreEqual(23, loaded2.Value);
                Assert.IsTrue(loaded2.in_VersionOf.Contains(e1.ORID));

                var loaded3 = database.Load.ORID(v3.ORID).Run<WidgetVersion>();
                Assert.IsNotNull(loaded3.in_VersionOf);
                Assert.AreEqual(1, loaded3.in_VersionOf.Count);
                Assert.AreEqual(34, loaded3.Value);
                Assert.IsTrue(loaded3.in_VersionOf.Contains(e2.ORID));

            }
        }
``` 

take look to test case of OrderedEdgesTest.cs

**Comment by amgiorgi** [comment]
Good morning Roman,
Thanks again for replying.

As you pointed out I can declare a property as HashSet(ORID) or List<ORID>
o in order to retrieve incoming or outgoing edges to a specific vertex.
That implies though that my model is known in advanced and all incoming and
outgoing edges are known. What if I don't want to statically map all my
classes? My database is currently changing very rapidly while we get along
converting all tables to classes from our previous InfiniDB based
datawarehouse. At this moment I would prefer to not work only with strong
types. Now using the REST protocol and dynamic objects we noticed that
@fieldTypes comfortably stores a list of out_ and in_ edges available for a
specific Document. We then proceed to code hyperlinks to linked Documents
knowing in advance what they were and the correct edge to traverse.

A quick example:
Here are two of our classes that are linked by an Edge in our database. It
refers to Hospital admissions.






























*public class Ricovero    {        [JsonProperty(PropertyName =
"@type")]        public string documentType {get; set;}
[JsonProperty(PropertyName = "@rid")]        public string RID {get;
set;}         [JsonProperty(PropertyName = "@version")]        public
string documentVersion {get; set;}         [JsonProperty(PropertyName =
"@class")]        public string className {get; set;}        public string
Nosologico {get; set;}        public DateTime DataRicovero {get;
set;}        public string AssistitoID {get; set;}        public short
DipendenzaRicovero { get; set; }        public string TipoRicovero { get;
set; }        public string[] out_Dimesso { get; set; }        public
string[] in_Ricoverato { get; set; }        public string RicoveratoIn {
get; set; }        public dynamic info { get; set; }        public
List<ORID> out_PrestazioneEffettuata { get; set; }
[JsonProperty(PropertyName = "@fieldTypes")]        public string
fieldTypes { get; set; }    }*








































*    public class Prestazioni    {        [JsonProperty("@type")]
public string Type { get; set; }        [JsonProperty("@rid")]
public string Rid { get; set; }        [JsonProperty("@version")]
public int Version { get; set; }        [JsonProperty("@class")]
public string Class { get; set; }
[JsonProperty("AssistitoID")]        public string AssistitoID { get; set;
}        [JsonProperty("DataPrestazione")]        public string
DataPrestazione { get; set; }
[JsonProperty("GiornoPrestazione")]        public int GiornoPrestazione {
get; set; }        [JsonProperty("Nosologico")]        public string
Nosologico { get; set; }        [JsonProperty("Prestazione")]        public
string Prestazione { get; set; }        [JsonProperty("Servizio")]
public string Servizio { get; set; }
[JsonProperty("in_PrestazioneEffettuata")]        public List<ORID>
InPrestazioneEffettuata { get; set; }
[JsonProperty("@fieldTypes")]        public string FieldTypes { get; set;
}    }*


//script below gets correctly outgoing edge PrestazioneEffettuata that
point to my class Prestazioni




* List<Ricovero> ricoveri = db.Query<Ricovero>("select from Ricoveri limit
10", "");                    foreach (Ricovero ric in
ricoveri)                    {                        lblResults.Text =
lblResults.Text + ric.AssistitoID.ToString() + "|" +
ric.out_PrestazioneEffettuata.Count().ToString() + "<br
/>";                    }*


What If instead not all my Documents have a predefined POCO?

Currently what I have tried is:


* private List<ODocument> documenti = new List<ODocument>();*

* documenti = db.Query("select from Ricoveri limit 10");*



*foreach(ODocument doc in documenti){*




*//how to go about finding outgoing and incoming
edges?doc.GetField<string>("@fieldTypes");  //this is not available*

*}*

**Comment by amgiorgi** [comment]
Apologies for the poorly formatted text. I replied from my mailbox and it came out this way.
I will post it again:

 public class Ricovero
    {

        [JsonProperty(PropertyName = "@type")]
        public string documentType {get; set;}

         [JsonProperty(PropertyName = "@rid")]
        public string RID {get; set;}

         [JsonProperty(PropertyName = "@version")]
        public string documentVersion {get; set;}

         [JsonProperty(PropertyName = "@class")]
        public string className {get; set;}

        public string Nosologico {get; set;}
        public DateTime DataRicovero {get; set;}
        public string AssistitoID {get; set;}
        public short DipendenzaRicovero { get; set; }
        public string TipoRicovero { get; set; }
        public string[] out_Dimesso { get; set; }
        public string[] in_Ricoverato { get; set; }
        public string RicoveratoIn { get; set; }
        public dynamic info { get; set; }
        public List<ORID> out_PrestazioneEffettuata { get; set; }

         [JsonProperty(PropertyName = "@fieldTypes")]
        public string fieldTypes { get; set; }
    }

    public class Prestazioni
    {

        [JsonProperty("@type")]
        public string Type { get; set; }

        [JsonProperty("@rid")]
        public string Rid { get; set; }

        [JsonProperty("@version")]
        public int Version { get; set; }

        [JsonProperty("@class")]
        public string Class { get; set; }

        [JsonProperty("AssistitoID")]
        public string AssistitoID { get; set; }

        [JsonProperty("DataPrestazione")]
        public string DataPrestazione { get; set; }

        [JsonProperty("GiornoPrestazione")]
        public int GiornoPrestazione { get; set; }

        [JsonProperty("Nosologico")]
        public string Nosologico { get; set; }

        [JsonProperty("Prestazione")]
        public string Prestazione { get; set; }

        [JsonProperty("Servizio")]
        public string Servizio { get; set; }

        [JsonProperty("in_PrestazioneEffettuata")]
        public List<ORID> InPrestazioneEffettuata { get; set; }

        [JsonProperty("@fieldTypes")]
        public string FieldTypes { get; set; }
    }



//script below gets correctly outgoing edge PrestazioneEffettuata that point to my class Prestazioni
               List<Ricovero> ricoveri = db.Query<Ricovero>("select from Ricoveri limit 10", "");
                    foreach (Ricovero ric in ricoveri)
                    {
                        lblResults.Text = lblResults.Text + ric.AssistitoID.ToString() + "|" + ric.out_PrestazioneEffettuata.Count().ToString() + "<br />";
                    }


What If instead not all my Documents have a predefined POCO?

Currently what I have tried is:

 private List<ODocument> documenti = new List<ODocument>();
 documenti = db.Query("select from Ricoveri limit 10");

foreach(ODocument doc in documenti)
{

//how to go about finding outgoing and incoming edges?
doc.GetField<string>("@fieldTypes");  //this is not available

}

**Comment by GoorMoon** [comment]
@amgiorgi,
Take a look to example that i created if this make sense ?
