### ISSUE TITLE
Null property will be instantiated during retrieving

### ISSUE THREAD

**Issue by gohsianghwee** [orientechnologies/OrientDB-NET.binary#58]
Hi,

My colleague encountered a problem whenever he tried to retrieve an object with one of the property was null. He figure out the null object was being instantiated. The bug has been fixed by him at https://github.com/cychua2015/OrientDB-NET.binary/commit/6bfe04e977068b75e490c5eb9b186858fab872cd. Please merge and we shall test again thereafter. Thanks.

Cordially,
Goh

**Comment by GrayDelacluyse** [comment]
@gohsianghwee if this is still a problem feel free to submit a pull request and we will evaluate.
