### ISSUE TITLE
Different properties with same class type save will cause incorrect value.

### ISSUE THREAD

**Issue by gohsianghwee** [orientechnologies/OrientDB-NET.binary#59]
Hi,

My colleague encountered a problem whenever he tried to retrieve save the object with 2 different properties with same class type. He figure out the data was not stored correct. The bug has been fixed by him at https://github.com/cychua2015/OrientDB-NET.binary/commit/6bfe04e977068b75e490c5eb9b186858fab872cd. Please merge and we shall test again thereafter. Thanks.

Cordially,
Goh

**Comment by GrayDelacluyse** [comment]
@gohsianghwee if this is still a problem feel free to submit a pull request and we will evaluate.
