### ISSUE TITLE
Error when getting stored dictionary

### ISSUE THREAD

**Issue by dagimf** [orientechnologies/OrientDB-NET.binary#62]
So i have a model, that stores a dictionary, it is part of the model, the storing process goes fine, no error, and when i get the data back it is  also good. The problem happens when i store a  dictionary with a single key pair value, then when i get it and try to convert it using the ODocuments to method it throws an exception (   'System.Collections.Generic.KeyValuePair`2[System.String,System.Object]' to type 'System.Collections.IDictionary'. ). I checked the db.
It stored it as {"key":value},

**Comment by GoorMoon** [comment]
@dagimf,

Which type is a value ?

**Comment by dagimf** [comment]
the type can be string, double, datetime, or bool. Ive tried it using string and number

**Comment by GoorMoon** [comment]
@dagimf,
Check test case, this is work for me

**Comment by dagimf** [comment]
ok will try the test and get back to you, thanks for the quick reply

**Comment by dagimf** [comment]
Very sorry for the late reply, so i run the test and it works perfectly.

 I noticed that in one of the new commits the document mapper in orient changes any object type to an ODocument. 
So before i updated orient client a dictionary of type <string, object> could be stored in the db easily, but now the document mapper is converting it to a dictionary of type <string, ODocument> and when i do this it casues an error ( 
Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,Orient.Client.ODocument]' to type 'System.Collections.Generic.IDictionary`2[System.String,System.Object]'.  
).
I can change the my dictionary to use string or double instead of object, but that will force me to split the dictionary into different types. So is there any solution for this, or should i start using a dictionary that is not <string, object>.

Thanks in avance

**Comment by GoorMoon** [comment]
@dagimf ,
Sorry but i don't understand your example do you have any test case ?

**Comment by dagimf** [comment]
so i have a form class like this,     

public class Form
    {
        public ORID ORID { get; set; }
        public string Type { get; set; }
        public Dictionary<string,object> FormData { get; set; }
    }

the object that is being stored looks like this,
Dictionary<string, object> dynamicData = new Dictionary<string, object>
            {
                { "timeNow", DateTime.Now },
                {"isFinished",false},{"isNecessary", true}, 
                { "Color", "red" }, 
                { "contrast to be used", "apk" }, 
                { "minimum Weigh", 334 },
                {
                    "Oxygen Level needed", 22
                }
            };
            var dynamicDataDto = new Form()
            {
                ORID = null,
                Type = "request",
                FormData = dynamicData
            };

Here is the TestCase I have written and tested (It fails when trying to store it to the db), 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Orient.Client;

namespace Orient.Tests.Issues
{
    [TestFixture()]
    public class TestingDictionaryOfStringObjectPair
    {
        [Test]
        public void AddingModelWithDictionaryOfStringObjectPairToDbAndCheckingStoredData()
        {
            using (TestDatabaseContext testContext = new TestDatabaseContext())
            using (var db = new ODatabase(TestConnection.GlobalTestDatabaseAlias))
            {
                var formClassName = "Form";

                var clusterid = db.Create.Class(formClassName).Run();
                var form = new Form();
                form.Type = "Test Form";
                form.ORID = null;
                form.FormData = new Dictionary<string, object>();
                //adding string to dictionary
                form.FormData.Add("String Test1", "Andrew");
                form.FormData.Add("String Test2", "Jack");
                //adding Guid to dictionary
                form.FormData.Add("Guid Test1", Guid.NewGuid());
                form.FormData.Add("Guid Test2", Guid.NewGuid());
                //adding Number to dictionary
                form.FormData.Add("Number Test1", 2);
                form.FormData.Add("Number Test2", 4);
                //adding Bool to dictionary
                form.FormData.Add("Bool Test1", false);
                form.FormData.Add("Bool Test2", true);
                //adding DateTime to dictionary
                form.FormData.Add("DateTime Test1", DateTime.Now);
                form.FormData.Add("DateTime Test2", DateTime.UtcNow);
                //adding the document to db
                var document = db.Insert(form).Into(formClassName).Run();

                var result = db.Query<Form>("SELECT * FROM " + formClassName).SingleOrDefault();

                Assert.AreEqual(form.Type, result.Type);

                // testing the string datas
                Assert.True(result.FormData.ContainsKey("String Test1"));
                Assert.True(result.FormData.ContainsKey("String Test2"));
                Assert.AreEqual(form.FormData["String Test1"], result.FormData["String Test1"]);
                Assert.AreEqual(form.FormData["String Test2"], result.FormData["String Test2"]);
                
                // testing the Guid datas
                Assert.True(result.FormData.ContainsKey("Guid Test1"));
                Assert.True(result.FormData.ContainsKey("Guid Test2"));
                Assert.AreEqual(form.FormData["Guid Test1"], result.FormData["Guid Test1"]);
                Assert.AreEqual(form.FormData["Guid Test2"], result.FormData["Guid Test2"]);

                // testing the Number datas
                Assert.True(result.FormData.ContainsKey("Number Test1"));
                Assert.True(result.FormData.ContainsKey("Number Test2"));
                Assert.AreEqual(form.FormData["Number Test1"], result.FormData["Number Test1"]);
                Assert.AreEqual(form.FormData["Number Test2"], result.FormData["Number Test2"]);

                // testing the Bool datas
                Assert.True(result.FormData.ContainsKey("Bool Test1"));
                Assert.True(result.FormData.ContainsKey("Bool Test2"));
                Assert.AreEqual(form.FormData["Bool Test1"], result.FormData["Bool Test1"]);
                Assert.AreEqual(form.FormData["Bool Test2"], result.FormData["Bool Test2"]);

                // testing the Datetime datas
                Assert.True(result.FormData.ContainsKey("DateTime Test1"));
                Assert.True(result.FormData.ContainsKey("DateTime Test2"));
                Assert.AreEqual(form.FormData["DateTime Test1"], result.FormData["Bool Test1"]);
                Assert.AreEqual(form.FormData["DateTime Test2"], result.FormData["DateTime Test2"]);
            }
        }

        public class Form
        {
            public ORID ORID { get; set; }
            public string Type { get; set; }
            public Dictionary<string, object> FormData { get; set; }
        }
    }
}

**Comment by GoorMoon** [comment]
@dagimf ,
Now i see the problem with property of type Dictionary<string,object> that driver can't guess the type  of returning entry in that property. Rewrite your test case with using ODocument instead.

**Comment by dagimf** [comment]
Thanks a lot, run the test and it works fine, also started using ODocument in my system as u suggested and it worked perfectly with no change required.

**Comment by GoorMoon** [comment]
Glad to hear
