### ISSUE TITLE
How to get ORID of object?

### ISSUE THREAD

**Issue by degustator** [orientechnologies/OrientDB-NET.binary#65]
Its more a question than issue

I want to use Orient in mixed mode. Somewhere I use ODocument queries, somewhere I use object updates for same documents etc

So at this moment I know some ORID and want to update object behind it.

{code}
String query = String.Format("select from {0} where ...");
documents = db.Query(query);
ODocument orientdoc = documents.FirstOrDefault();
{code}

And now I want to update  the object that stands behind this doc using  construction below. I actuallywant to replace its current value to a completely new data from just created instance) 

{code}
int documentUpdated = db.Update(some_class_object).Run();
{code}

It throws NullPointer exception because id doesn't know ORID. How can I set existing ORDI to some new object instance?

Thanks in advance!

**Comment by GoorMoon** [comment]
@degustator ,
What type is some_class_object ?
