### ISSUE TITLE
ReadByte issue with OrientDB 2.0rc

### ISSUE THREAD

**Issue by jiujiu1123** [orientechnologies/OrientDB-NET.binary#7]
I have been using this driver for version 1.7.9, but when I update to OrientDB 2.0rc, the driver can no longer be functional. 
The driver just hangs when calling Response.Receive() method, More specifically on 
```c-sharp
Status = (ResponseStatus)reader.ReadByte();  
```
I am using the latest version of this driver on the Master branch.

**Comment by Sandra121289** [comment]
The same issue occurs for me too.

**Comment by jiujiu1123** [comment]
the new version appears to be working for me

**Comment by Sandra121289** [comment]
Yes, for me too. The newest code version does not hang anymore :)

**Comment by GoorMoon** [comment]
Thanks guys, i close this issue for now.
if someone has problem in the features please comment.
