### ISSUE TITLE
ORID does not conform to .NET naming conventions

### ISSUE THREAD

**Issue by cwaldron** [orientechnologies/OrientDB-NET.binary#73]
The all upper case class name "ORID" should be modified to "Orid" to conform with standard .NET naming conventions and guidelines.

**Comment by silverfox1948** [comment]
@cwaldron   
It's fairly common to use standard capitalized domain space acronyms (of which ORID is one) as all capitals in C#. I believe in this case ORID is perfectly fine.

**Comment by cwaldron** [comment]
Names of Classes, Structs, and Interfaces
The naming guidelines that follow apply to general type naming.
✓ DO name classes and structs with nouns or noun phrases, using PascalCasing.
This distinguishes type names from methods, which are named with verb phrases.

https://msdn.microsoft.com/en-us/library/ms229040(v=vs.110).aspx

**Comment by GrayDelacluyse** [comment]
The work is being shifted into the the driver.
