### ISSUE TITLE
Can't find cluster id if cluster name and class name are different

### ISSUE THREAD

**Issue by jiujiu1123** [orientechnologies/OrientDB-NET.binary#8]
Lately I have to change the name for one of my class so I executed the following command.
```sql
ALTER CLASS Users NAME user
```
Then when I try to access it using the following code it throws an exception.
```csharp
using (var database = Settings.GetDatabase())
{
    database
        .Create
        .Vertex("user")
        .Run();
}
```
This is a screen shot of the code that threw the exception.
![default](https://cloud.githubusercontent.com/assets/8244605/5565975/948aa11c-8f67-11e4-9b30-da5359df3faa.png)
As you can see the class name and the cluster name is not the same, but the driver is try to match the cluster id with the class name.

This is the link for the exported version of my test database/
https://onedrive.live.com/redir?resid=A926F63081BDBEAF%213230

**Comment by GoorMoon** [comment]
The problem that "ALTER CLASS Users NAME user" does not reload clusters (That i manage locally for performance). I think driver should provide reload clusters method on ODatabase class for such cases.

**Comment by GoorMoon** [comment]
@jiujiu1123 , can you confirm and close the issue ?

**Comment by GoorMoon** [comment]
If you still have issue please comment here.
