### ISSUE TITLE
Is record level security implementeed ??

### ISSUE THREAD

**Issue by dagimf** [orientechnologies/OrientDB-NET.binary#93]
hello i was just wondering if record level security is implemented in the binary, i tried looking for an implementation for the ORestricted class and could not find it.

If its not implemented , then i was thinking of using clusters as a sandboxing security. Woiuld love your inputs. Thanks in advance,

**Comment by luigidellaquila** [comment]
Hi @dagimf 

Record level security is implemented on the server side, so it does not depend on the client. I'd say you can use it without any problems

Thanks

Luigi

**Comment by dagimf** [comment]
Thanks Man.
